# Generated by Django 3.1.6 on 2021-04-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
